
fastlane_version "1.13.0"

default_platform :mac

platform :mac do

  sh "cd .. && apiary preview --output=docs.html"
  message = prompt(text: "Commit message: ")
  sh "cd .. && git commit -am \"#{message}\" && git push"

end
