
fastlane_version "1.13.0"

lane :push do
	sh "cd .. && apiary preview --output=docs.html"
	message = prompt(text: "Commit message: ")
	sh "cd .. && git add . && git commit -am \"#{message}\" && git push"
end
